name: 'xero'
version: '1.0.1'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]

vars:
  xero:
    account: "{{ source('xero', 'account') }}"
    contact: "{{ source('xero', 'contact') }}"
    invoice_line_item: "{{ source('xero', 'invoice_line_item') }}"
    invoice: "{{ source('xero', 'invoice') }}"
    journal_line: "{{ source('xero', 'journal_line') }}"
    journal: "{{ source('xero', 'journal') }}"
    organization: "{{ source('xero', 'organization') }}"
    credit_note: "{{ source('xero', 'credit_note') }}"
    bank_transaction: "{{ source('xero', 'bank_transaction') }}"
    invoice_line_item_has_tracking_category: "{{ source('xero', 'invoice_line_item_has_tracking_category') }}"
    journal_line_has_tracking_category: "{{ source('xero', 'journal_line_has_tracking_category') }}"
    tracking_category_has_option: "{{ source('xero', 'tracking_category_has_option') }}"
    tracking_category_option: "{{ source('xero', 'tracking_category_option') }}"
    tracking_category: "{{ source('xero', 'tracking_category') }}"
    xero__using_bank_transaction: true
    xero__using_credit_note: true

models:
  xero:
    +materialized: table
    +schema: xero
    utilities:
      +materialized: ephemeral
    staging:
      +schema: stg_xero
      +materialized: table
      tmp:
        +materialized: view
