name: 'xero'
version: '0.3.0'
config-version: 2
require-dbt-version: ">=0.20.0"

vars:
  xero:
    account: "{{ ref('stg_xero__account') }}"
    contact: "{{ ref('stg_xero__contact') }}"
    invoice_line_item: "{{ ref('stg_xero__invoice_line_item') }}"
    invoice: "{{ ref('stg_xero__invoice') }}"
    journal_line: "{{ ref('stg_xero__journal_line') }}"
    journal: "{{ ref('stg_xero__journal') }}"
    organization: "{{ ref('stg_xero__organization') }}"
    credit_note: "{{ ref('stg_xero__credit_note') }}"
    bank_transaction: "{{ ref('stg_xero__bank_transaction') }}"
    purchase_order_line_item: "{{ ref('stg_xero__purchase_order_line_item') }}"
    purchase_order: "{{ ref('stg_xero__purchase_order') }}"

models:
  xero:
    +materialized: table
    +schema: xero
    utilities:
      +materialized: ephemeral
