name: 'xero_integration_tests'
version: '1.0.0'
profile: 'integration_tests'
config-version: 2

vars: 
  xero_source:
    account: "{{ ref('xero_account_data') }}"
    journal_line: "{{ ref('xero_journal_line_data') }}"
    journal: "{{ ref('xero_journal_data') }}"