name: 'xero_integration_tests'
version: '0.5.0'
profile: 'integration_tests'
config-version: 2

vars: 
  xero_source:
    xero__account_identifier: "xero_account_data"
    xero__journal_line_identifier: "xero_journal_line_data"
    xero__journal_identifier: "xero_journal_data"
    xero__contact_identifier: "xero_contact_data"
    xero__invoice_identifier: "xero_invoice_data"
    xero__invoice_line_item_identifier: "xero_invoice_line_item_data"
    xero__organization_identifier: "xero_organization_data"
    xero__credit_note_identifier: "xero_credit_note_data"
    xero__bank_transaction_identifier: "xero_bank_transaction_data"
  xero_schema: xero_integration_tests