name: 'xero_integration_tests'
version: '0.9.0'
profile: 'integration_tests'
config-version: 2

vars:
  xero_source:
    xero_account_identifier: "xero_account_data"
    xero_contact_identifier: "xero_contact_data"
    xero_invoice_line_item_identifier: "xero_invoice_line_item_data"
    xero_invoice_identifier: "xero_invoice_data"
    xero_journal_line_identifier: "xero_journal_line_data"
    xero_journal_identifier: "xero_journal_data"
    xero_organization_identifier: "xero_organization_data"
    xero_bank_transaction_identifier: "xero_bank_transaction_data"
    xero_credit_note_identifier: "xero_credit_note_data"
    xero_invoice_line_item_has_tracking_category_identifier: "xero_invoice_line_item_has_tracking_category_data"
    xero_journal_line_has_tracking_category_identifier: "xero_journal_line_has_tracking_category_data"
    xero_tracking_category_identifier: "xero_tracking_category_data"
    xero_tracking_category_has_option_identifier: "xero_tracking_category_has_option_data"
    xero_tracking_category_option_identifier: "xero_tracking_category_option_data"    
  xero_schema: xero_integration_tests_7

models:
  +schema: "xero_{{ var('directed_schema','dev') }}"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']