name: 'xero_integration_tests'
version: '0.1.0'
profile: 'integration_tests'
config-version: 2

vars: 
  xero_source:
    account: "{{ ref('xero_account_data') }}"
    journal_line: "{{ ref('xero_journal_line_data') }}"
    journal: "{{ ref('xero_journal_data') }}"
    contact: "{{ ref('xero_contact_data') }}"
    invoice: "{{ ref('xero_invoice_data') }}"
    invoice_line_item: "{{ ref('xero_invoice_line_item_data') }}"
    organization: "{{ ref('xero_organization_data') }}"